#!/bin/sh
# -*- mode: sh -*-

# nearest mirror
MIRROR=http://downloads.sourceforge.net/project/opm-project

# import repository key
if [ ! -f /etc/pki/rpm-gpg/RPM-GPG-KEY-OPM ]; then
    wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-OPM http://www.opm-project.org/packages/current/redhat/6/RPM-GPG-KEY-OPM
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OPM
fi

# add .repo file
if [ ! -f /etc/yum.repos.d/opm.repo ]; then
    cat >> /etc/yum.repos.d/opm.repo <<EOF
[opm]
name=Open Porous Media Initiative
baseurl=$MIRROR/packages/2013.09/redhat/\$releasever
gpgkey=
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OPM
EOF
fi
