#!/bin/sh
# -*- mode: sh -*-

# nearest mirror
PUIAS=http://ftp.heanet.ie/pub/puias

# import repository key; seems to be the same between 32- and 64-bits
if [ ! -f /etc/pki/rpm-gpg/RPM-GPG-KEY-puias ]; then
    wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-puias $PUIAS/5/en/os/i386/RPM-GPG-KEY
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-puias
fi

# add .repo file
if [ ! -f /etc/yum.repos.d/puias.repo ]; then
    cat >> /etc/yum.repos.d/puias.repo <<EOF
[puias-computational]
name=PUIAS computational Base \$releasever - \$basearch
baseurl=$PUIAS/computational/\$releasever/\$basearch
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puias
EOF
fi
