#!/bin/sh
# -*- mode: sh -*-

# make sure that we have everything we need in place;
# this script will also set the variable bldtree
source $(dirname $0)/download_prereqs

# build each source package
for specfile in $bldtree/SPECS/*.spec; do
    rpmbuild --define "_topdir $bldtree" -bs $specfile
done
