#!/bin/sh
# -*- mode: sh -*-

# make sure that we have everything we need in place;
# this script will also set the variable bldtree
source $(dirname $0)/download_prereqs

# patch .spec files so they can be used on RHEL5
$(dirname $0)/is_on_rhel5 && source $(dirname $0)/make_rhel5_compat

# build each source package
for specfile in $bldtree/SPECS/*.spec; do
    rpmbuild --define "_topdir $bldtree" -bs $specfile
done
